### ISSUE TITLE
关于 svg 渲染和显示

### ISSUE THREAD

**Issue by MuYunyun** [MuYunyun/cpreact#7]
svg 元素在页面渲染出来了，但是页面中没有显示出来

```js
class App extends Component {
  render() {
    return (
      <div>
        12345
        <svg>
          <circle cx={20} cy={20} r={20} fill='blue' />
        </svg>
      </div>
    )
  }
}
```

![image](https://user-images.githubusercontent.com/19354791/45796908-6eeecd80-bcd5-11e8-822d-f7b670cc9a97.png)

**Comment by shinken008** [comment]
reference[https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course](url)

**Comment by MuYunyun** [comment]
@shinken008 ~~和 Namespaces 没关系的，~~

![image](https://user-images.githubusercontent.com/19354791/46913460-eb688980-cfbf-11e8-9df6-b18858398fe8.png)

**Comment by MuYunyun** [comment]
@shinken008 确实和命名空间有关系，上述直接在属性上加上 `xmlns="http://www.w3.org/2000/svg"` 不成功猜测浏览器在 <!doctype html> 声明下当成无效的字符串来对待了，目前解决思路是使用 `document.createElementNS('http://www.w3.org/2000/svg', vdom.nodeName)` 这个 api：

```js
if (vdom.nodeName === 'svg' || vdom.isSVGElement) {
  dom = document.createElementNS('http://www.w3.org/2000/svg', vdom.nodeName)
  for (let i = 0; i < vdom.children.length; i++) {
    vdom.children[i].isSVGElement = true
  }
} else {
  dom = document.createElement(vdom.nodeName)
}
```
